# File: .streamlit/secrets.toml
# NON condividere questo file! Aggiungilo al .gitignore

GEMINI_API_KEY = AIzaSyBJ9S-njoq5EhZjms4lsTTIt5_Ki9vcpWc

GOOGLE_CREDENTIALS = '''
{
  "type": "service_account",
  "project_id": "il-tuo-project-id",
  "private_key_id": "...",
  "private_key": "-----BEGIN RSA PRIVATE KEY-----\n...\n-----END RSA PRIVATE KEY-----\n",
  "client_email": "il-tuo-service-account@project.iam.gserviceaccount.com",
  "client_id": "...",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "..."
}
'''
